name: CI

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  broken_links:
    name: Detect Broken Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress 'docs/**/*.md' --exclude-loopback
          format: markdown
          jobSummary: true
          fail: true
