name: CI

on:
  pull_request:

jobs:
  broken_links:
    name: Detect Broken Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          format: markdown
          jobSummary: true
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
